version: '3.7'

x-logging:
    &default-json-logging
    driver: json-file
    options:
        max-file: "3"
        max-size: "10m"

services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: Asia/Tokyo
    image: jupyterlab
    restart: always
    container_name: jupyterlab
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./workspace:/home/labuser/work
    ports:
      - 18580:8888
    logging: *default-json-logging
